ARG WHOAMI
FROM ${WHOAMI}/dl

# build xgboost (with gpu support)
# https://xgboost.readthedocs.io/en/latest/build.html#building-with-gpu-support
WORKDIR /opt
RUN git clone --recursive https://github.com/dmlc/xgboost
RUN mkdir -p /opt/xgboost/build
WORKDIR /opt/xgboost/build
## pick one of the following build method
# 1/ no gpu support
# RUN cmake .. && make -j4
# 2/ with single gpu support
RUN cmake .. -DUSE_CUDA=ON && make -j4
# 3/ with multi-gpu support (need to install nccl2 from https://developer.nvidia.com/nccl)
# RUN cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_ROOT=/path/to/nccl2 && make -j4
# install xgboost for python
WORKDIR /opt/xgboost/python-package
RUN python setup.py install

# TODO build lightgbm
# https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-gpu-version
# https://pypi.org/project/lightgbm/
# WORKDIR /opt
# pip install lightgbm --install-option=--gpu

# install dask-xgboost from pip
RUN pip install -U dask-xgboost

# clean up
RUN rm -rf /tmp/*
RUN /opt/conda/bin/conda clean -ya

# set default directory
WORKDIR /workspace
