version: "3"

services:
  db-postgres:
    image: postgres:alpine
    # container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

